### ISSUE TITLE
[refactoring]: jd2gcal

### ISSUE THREAD

**Issue by kkdd** [phn/jdcal#9]
I would suggest to refactor ```jd2gcal```. See ```mjd2date(mjd)``` below:

```
$ pip install jdcal
$ ./test_jdcal.py
 passed
```

```
$ cat test_jdcal.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
from jdcal import jd2gcal

def test():
    for mjd in range(146097):
        w = {jd2gcal: jd2gcal(2400000.5, mjd)[:3], mjd2date: mjd2date(mjd)}
        if w['jd2gcal']!=w['mjd2date']:
            print(w['jd2gcal'], "!=", w['mjd2date'])
            return
    print(' passed')

# conversion from modified Julian date to Gregorian calendar date 
def mjd2date(mjd):
    n = mjd + 678881  # Gregorian
    a = 4*n + 3
    a += 4*((3*((4*(n+1))//146097+1))//4)  # Gregorian
    b = 5*((a%1461)//4) + 2
    year, month, day = a//1461, b//153 + 3, (b%153)//5 + 1
    if month > 12:
        year, month = year+1, month%12
    return year, month, day

test()
```

**Comment by kkdd** [comment]
Hello,
The Gregorian-specific term, ```4*((3*((4*(n+1))//146097+1))//4)```, in the equation is reformed and obtained from 
https://en.wikipedia.org/wiki/Julian_day#Julian_or_Gregorian_calendar_from_Julian_day_number

**Comment by phn** [comment]
Hello @kkdd , @Yei9311 , 

@kkdd About refractoring code.

Sorry for taking 3 years to reply!

As mentioned in the readme I was following very closely the code from a code base (in C) that 
was successfully being used to do calculations while running a telescope. I want to 
preserve this close match and so unless there is an error or a significant boost in performance
I am not inclined towards a refactoring. But I appreciate your effort in suggesting these 
changes.

@Yei9311 About formula

You can use the formula given by @kkdd . You will notice the formula in Python code 
is the same formula but carried out in multiple steps and uses `int` instead of 
`\\` to do truncate values to integers. The code also takes steps to consider that 
jd has 2 parts. @kkdd thank you for listing link to the formula.
